# Generated by Django 4.0.6 on 2022-07-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='점포명')),
                ('address', models.CharField(max_length=50, verbose_name='주소')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('hardness', models.FloatField(verbose_name='경도')),
            ],
        ),
    ]
