# Generated by Django 4.0.6 on 2022-07-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_hardness_alter_restaurant_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='number',
            field=models.CharField(default=1, max_length=50, verbose_name='관리번호'),
            preserve_default=False,
        ),
    ]
