# Generated by Django 4.0.6 on 2022-07-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='gu',
            field=models.CharField(default=1, max_length=50, verbose_name='구'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=100, verbose_name='주소'),
        ),
    ]
