# Generated by Django 4.0.6 on 2022-07-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_gu_alter_restaurant_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='gu',
            new_name='dong',
        ),
    ]
