# Generated by Django 4.0.6 on 2022-07-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_restaurant_number_restaurant_road_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='road_address',
        ),
    ]
