# Generated by Django 4.0.6 on 2022-07-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_remove_restaurant_road_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=100, verbose_name='도로명 주소'),
        ),
    ]
