# Generated by Django 4.0.6 on 2022-07-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_restaurant_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='dong',
            field=models.CharField(max_length=50, verbose_name='동'),
        ),
    ]
