# Generated by Django 4.0.6 on 2022-07-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_restaurant_dong'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='blog_reviews',
            field=models.IntegerField(default=1, verbose_name='블로그 리뷰수'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='visitor_reviews',
            field=models.IntegerField(default=1, verbose_name='방문자 리뷰수'),
            preserve_default=False,
        ),
    ]
