# Generated by Django 4.0.6 on 2022-07-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_restaurant_blog_reviews_restaurant_visitor_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='total_counts',
            field=models.IntegerField(default=1, verbose_name='전체 리뷰수'),
            preserve_default=False,
        ),
    ]
