# Generated by Django 4.0.6 on 2022-07-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_top_10_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_10_res',
            name='current',
            field=models.CharField(default=1, max_length=50, verbose_name='현재 위도 경도'),
            preserve_default=False,
        ),
    ]
