# Generated by Django 4.0.6 on 2022-07-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_alter_top_10_res_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='link',
            field=models.TextField(default=1, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
